import { BrandTitle, BrandTitle2 } from "../lib/Lib";

export default function PrivacyPolicy() {
  return (
    <div className="md:mx-10 mt-3 mx-4 flex justify-center">
      <div className="lg:max-w-[80%] font-sans">
        <h1 className="pb-4 mb-2 inline-block text-2xl font-bold tracking-tight text-gray-800 dark:text-white font-roboto">Privacy Policy for <span className="text-blue-500 hover:underline cursor-default"><BrandTitle /></span></h1>
        <p className="mb-2 text-lg dark:text-gray-300 text-justify"><span className="ml-5" />At <span className="text-blue-500 hover:underline cursor-default"><BrandTitle2 /></span>, accessible from {window.location.origin}, one of our main priorities is the privacy of our visitors. This Privacy Policy document contains types of information that is collected and recorded by <span className="text-blue-500 hover:underline cursor-default"><BrandTitle2 /></span> and how we use it.</p>
        <p className="mb-2 text-lg dark:text-gray-300 text-justify"><span className="ml-5 md:ml-0" />If you have additional questions or require more information about our Privacy Policy, do not hesitate to contact us.</p>
        <hr className="border dark:border-gray-200 border-gray-500" />
        <h2 className="relative group text-2xl font-semibold mt-8 mb-4 dark:text-gray-100">Log Files</h2>
        <p className="mb-2 text-base dark:text-gray-300 text-justify"><span className="ml-5" /><span className="text-blue-500 hover:underline cursor-default"><BrandTitle2 /></span> follows a standard procedure of using log files. These files log visitors when they visit websites. All hosting companies do this and a part of hosting services' analytics. The information collected by log files include internet protocol (IP) addresses, browser type, Internet Service Provider (ISP), date and time stamp, referring/exit pages, and possibly the number of clicks. These are not linked to any information that is personally identifiable. The purpose of the information is for analyzing trends, administering the site, tracking users' movement on the website, and gathering demographic information. Our Privacy Policy was created with the help of the <a href="https://www.privacypolicyonline.com/privacy-policy-generator/">Privacy Policy Generator</a>.</p>
        <h2 className="relative group text-2xl font-semibold mt-8 mb-4 dark:text-gray-100">Privacy Policies</h2>
        <p className="mb-4 text-base dark:text-gray-300 text-justify"><span className="ml-5 md:ml-0" />You may consult this list to find the Privacy Policy for each of the advertising partners of <span className="text-blue-500 hover:underline cursor-default"><BrandTitle2 /></span>.</p>
        <p className="mb-4 text-base dark:text-gray-300 text-justify"><span className="ml-5" />Third-party ad servers or ad networks uses technologies like cookies, JavaScript, or Web Beacons that are used in their respective advertisements and links that appear on <span className="text-blue-500 hover:underline cursor-default"><BrandTitle2 /></span>, which are sent directly to users' browser. They automatically receive your IP address when this occurs. These technologies are used to measure the effectiveness of their advertising campaigns and/or to personalize the advertising content that you see on websites that you visit.</p>
        <p className="mb-4 text-base dark:text-gray-300 text-justify"><span className="ml-5 md:ml-0" />Note that <span className="text-blue-500 hover:underline cursor-default"><BrandTitle2 /></span> has no access to or control over these cookies that are used by third-party advertisers.</p>
        <h2 className="relative group text-2xl font-semibold mt-8 mb-4 dark:text-gray-100">Third Party Privacy Policies</h2>
        <p className="mb-4 text-base dark:text-gray-300 text-justify"><span className="ml-5" /><span className="text-blue-500 hover:underline cursor-default"><BrandTitle2 /></span>'s Privacy Policy does not apply to other advertisers or websites. Thus, we are advising you to consult the respective Privacy Policies of these third-party ad servers for more detailed information. It may include their practices and instructions about how to opt-out of certain options. </p>
        <p className="mb-4 text-base dark:text-gray-300 text-justify"><span className="ml-5" />You can choose to disable cookies through your individual browser options. To know more detailed information about cookie management with specific web browsers, it can be found at the browsers' respective websites. What Are Cookies?</p>
        <h2 className="relative group text-2xl font-semibold mt-8 mb-4 dark:text-gray-100">Children's Information</h2>
        <p className="mb-4 text-base dark:text-gray-300 text-justify"><span className="ml-5" />Another part of our priority is adding protection for children while using the internet. We encourage parents and guardians to observe, participate in, and/or monitor and guide their online activity.</p>
        <p className="mb-4 text-base dark:text-gray-300 text-justify"><span className="ml-5" /><span className="text-blue-500 hover:underline cursor-default"><BrandTitle2 /></span> does not knowingly collect any Personal Identifiable Information from children under the age of 13. If you think that your child provided this kind of information on our website, we strongly encourage you to contact us immediately and we will do our best efforts to promptly remove such information from our records.</p>
        <h2 className="relative group text-2xl font-semibold mt-8 mb-4 dark:text-gray-100">Online Privacy Policy Only</h2>
        <p className="mb-4 text-base dark:text-gray-300 text-justify"><span className="ml-5" />This Privacy Policy applies only to our online activities and is valid for visitors to our website with regards to the information that they shared and/or collect in <span className="text-blue-500 hover:underline cursor-default"><BrandTitle2 /></span>. This policy is not applicable to any information collected offline or via channels other than this website.</p>
        <h2 className="relative group text-2xl font-semibold mt-8 mb-4 dark:text-gray-100">Consent</h2>
        <p className="mb-4 text-base dark:text-gray-300 text-justify"><span className="ml-5 md:ml-0" />By using our website, you hereby consent to our Privacy Policy and agree to its Terms and Conditions.</p>
      </div>
    </div>
  );
}
